version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:13.1-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=katyush2_admin
      - POSTGRES_PASSWORD=katyusha@dmin2023
      - POSTGRES_DB=katyush2_db
    ports:
        - "5432:5432"
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend


volumes:
  db:
  static_volume:
  media_volume:
